##### Copyright 2019 The TensorFlow Authors.


In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 用 tf.data 加载 CSV 数据

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://tensorflow.google.cn/tutorials/load_data/csv"><img src="https://tensorflow.google.cn/images/tf_logo_32px.png" />在 Tensorflow.org 上查看</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs-l10n/blob/master/site/zh-cn/tutorials/load_data/csv.ipynb"><img src="https://tensorflow.google.cn/images/colab_logo_32px.png" />在 Google Colab 运行</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs-l10n/blob/master/site/zh-cn/tutorials/load_data/csv.ipynb"><img src="https://tensorflow.google.cn/images/GitHub-Mark-32px.png" />在 Github 上查看源代码</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs-l10n/site/zh-cn/tutorials/load_data/csv.ipynb"><img src="https://tensorflow.google.cn/images/download_logo_32px.png" />下载此 notebook</a>
  </td>
</table>

Note: 我们的 TensorFlow 社区翻译了这些文档。因为社区翻译是尽力而为， 所以无法保证它们是最准确的，并且反映了最新的
[官方英文文档](https://tensorflow.google.cn/?hl=en)。如果您有改进此翻译的建议， 请提交 pull request 到
[tensorflow/docs](https://github.com/tensorflow/docs) GitHub 仓库。要志愿地撰写或者审核译文，请加入
[docs-zh-cn@tensorflow.org Google Group](https://groups.google.com/a/tensorflow.org/forum/#!forum/docs-zh-cn)。

这篇教程通过一个示例展示了怎样将 CSV 格式的数据加载进 `tf.data.Dataset`。

这篇教程使用的是泰坦尼克号乘客的数据。模型会根据乘客的年龄、性别、票务舱和是否独自旅行等特征来预测乘客生还的可能性。

## 设置

In [2]:
import functools

import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds

In [3]:
TRAIN_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/train.csv"
TEST_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/eval.csv"

train_file_path = tf.keras.utils.get_file("train.csv", TRAIN_DATA_URL)
test_file_path = tf.keras.utils.get_file("eval.csv", TEST_DATA_URL)

 8192/30874 [======>.......................] - ETA: 0s

30874/30874 [==============================] - 0s 0us/step


 8192/13049 [=================>............] - ETA: 0s

13049/13049 [==============================] - 0s 0us/step


In [4]:
# 让 numpy 数据更易读。
np.set_printoptions(precision=3, suppress=True)

## 加载数据

开始的时候，我们通过打印 CSV 文件的前几行来了解文件的格式。

In [5]:
!head {train_file_path}

survived,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone
0,male,22.0,1,0,7.25,Third,unknown,Southampton,n
1,female,38.0,1,0,71.2833,First,C,Cherbourg,n
1,female,26.0,0,0,7.925,Third,unknown,Southampton,y
1,female,35.0,1,0,53.1,First,C,Southampton,n
0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y
0,male,2.0,3,1,21.075,Third,unknown,Southampton,n
1,female,27.0,0,2,11.1333,Third,unknown,Southampton,n
1,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n
1,female,4.0,1,1,16.7,Third,G,Southampton,n


正如你看到的那样，CSV 文件的每列都会有一个列名。dataset 的构造函数会自动识别这些列名。如果你使用的文件的第一行不包含列名，那么需要将列名通过字符串列表传给 `make_csv_dataset` 函数的 `column_names` 参数。

 



```python

CSV_COLUMNS = ['survived', 'sex', 'age', 'n_siblings_spouses', 'parch', 'fare', 'class', 'deck', 'embark_town', 'alone']

dataset = tf.data.experimental.make_csv_dataset(
     ...,
     column_names=CSV_COLUMNS,
     ...)
  
```


这个示例使用了所有的列。如果你需要忽略数据集中的某些列，创建一个包含你需要使用的列的列表，然后传给构造器的（可选）参数 `select_columns`。

```python

dataset = tf.data.experimental.make_csv_dataset(
  ...,
  select_columns = columns_to_use, 
  ...)

```

对于包含模型需要预测的值的列是你需要显式指定的。

In [6]:
LABEL_COLUMN = 'survived'
LABELS = [0, 1]

现在从文件中读取 CSV 数据并且创建 dataset。

(完整的文档，参考 `tf.data.experimental.make_csv_dataset`)


In [7]:
def get_dataset(file_path):
  dataset = tf.data.experimental.make_csv_dataset(
      file_path,
      batch_size=12, # 为了示例更容易展示，手动设置较小的值
      label_name=LABEL_COLUMN,
      na_value="?",
      num_epochs=1,
      ignore_errors=True)
  return dataset

raw_train_data = get_dataset(train_file_path)
raw_test_data = get_dataset(test_file_path)

dataset 中的每个条目都是一个批次，用一个元组（*多个样本*，*多个标签*）表示。样本中的数据组织形式是以列为主的张量（而不是以行为主的张量），每条数据中包含的元素个数就是批次大小（这个示例中是 12）。

阅读下面的示例有助于你的理解。

In [8]:
examples, labels = next(iter(raw_train_data)) # 第一个批次
print("EXAMPLES: \n", examples, "\n")
print("LABELS: \n", labels)

EXAMPLES: 
 OrderedDict([('sex', <tf.Tensor: shape=(12,), dtype=string, numpy=
array([b'female', b'female', b'male', b'male', b'female', b'male',
       b'female', b'male', b'female', b'male', b'female', b'male'],
      dtype=object)>), ('age', <tf.Tensor: shape=(12,), dtype=float32, numpy=
array([28., 41., 28., 24., 63., 28., 28., 65., 34.,  9., 27., 30.],
      dtype=float32)>), ('n_siblings_spouses', <tf.Tensor: shape=(12,), dtype=int32, numpy=array([1, 0, 0, 0, 1, 0, 0, 0, 0, 5, 0, 0], dtype=int32)>), ('parch', <tf.Tensor: shape=(12,), dtype=int32, numpy=array([0, 5, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0], dtype=int32)>), ('fare', <tf.Tensor: shape=(12,), dtype=float32, numpy=
array([82.171, 39.688,  7.896,  7.896, 77.958,  7.896,  7.75 , 61.979,
       23.   , 46.9  ,  7.925, 27.75 ], dtype=float32)>), ('class', <tf.Tensor: shape=(12,), dtype=string, numpy=
array([b'First', b'Third', b'Third', b'Third', b'First', b'Third',
       b'Third', b'First', b'Second', b'Third', b'Third', b'First']

## 数据预处理

### 分类数据

CSV 数据中的有些列是分类的列。也就是说，这些列只能在有限的集合中取值。

使用 `tf.feature_column` API 创建一个 `tf.feature_column.indicator_column` 集合，每个 `tf.feature_column.indicator_column` 对应一个分类的列。


In [9]:
CATEGORIES = {
    'sex': ['male', 'female'],
    'class' : ['First', 'Second', 'Third'],
    'deck' : ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'embark_town' : ['Cherbourg', 'Southhampton', 'Queenstown'],
    'alone' : ['y', 'n']
}


In [10]:
categorical_columns = []
for feature, vocab in CATEGORIES.items():
  cat_col = tf.feature_column.categorical_column_with_vocabulary_list(
        key=feature, vocabulary_list=vocab)
  categorical_columns.append(tf.feature_column.indicator_column(cat_col))

In [11]:
# 你刚才创建的内容
categorical_columns

[IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='sex', vocabulary_list=('male', 'female'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='class', vocabulary_list=('First', 'Second', 'Third'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='deck', vocabulary_list=('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='embark_town', vocabulary_list=('Cherbourg', 'Southhampton', 'Queenstown'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='alone', vocabulary_list=('y', 'n'), dtype=tf.string, default_value=-1, num_oov_buckets=0))]

这将是后续构建模型时处理输入数据的一部分。

### 连续数据

连续数据需要标准化。

写一个函数标准化这些值，然后将这些值改造成 2 维的张量。


In [12]:
def process_continuous_data(mean, data):
  # 标准化数据
  data = tf.cast(data, tf.float32) * 1/(2*mean)
  return tf.reshape(data, [-1, 1])

现在创建一个数值列的集合。`tf.feature_columns.numeric_column` API 会使用 `normalizer_fn` 参数。在传参的时候使用  [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial)，`functools.partial` 由使用每个列的均值进行标准化的函数构成。

In [13]:
MEANS = {
    'age' : 29.631308,
    'n_siblings_spouses' : 0.545455,
    'parch' : 0.379585,
    'fare' : 34.385399
}

numerical_columns = []

for feature in MEANS.keys():
  num_col = tf.feature_column.numeric_column(feature, normalizer_fn=functools.partial(process_continuous_data, MEANS[feature]))
  numerical_columns.append(num_col)

In [14]:
# 你刚才创建的内容。
numerical_columns

[NumericColumn(key='age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=functools.partial(<function process_continuous_data at 0x7f74fc4f8c10>, 29.631308)),
 NumericColumn(key='n_siblings_spouses', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=functools.partial(<function process_continuous_data at 0x7f74fc4f8c10>, 0.545455)),
 NumericColumn(key='parch', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=functools.partial(<function process_continuous_data at 0x7f74fc4f8c10>, 0.379585)),
 NumericColumn(key='fare', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=functools.partial(<function process_continuous_data at 0x7f74fc4f8c10>, 34.385399))]

这里使用标准化的方法需要提前知道每列的均值。如果需要计算连续的数据流的标准化的值可以使用 [TensorFlow Transform](https://tensorflow.google.cn/tfx/transform/get_started)。

### 创建预处理层

将这两个特征列的集合相加，并且传给 `tf.keras.layers.DenseFeatures` 从而创建一个进行预处理的输入层。

In [15]:
preprocessing_layer = tf.keras.layers.DenseFeatures(categorical_columns+numerical_columns)

## 构建模型

从 `preprocessing_layer` 开始构建 `tf.keras.Sequential`。

In [16]:
model = tf.keras.Sequential([
  preprocessing_layer,
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid'),
])

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy'])

## 训练、评估和预测

现在可以实例化和训练模型。

In [17]:
train_data = raw_train_data.shuffle(500)
test_data = raw_test_data

In [18]:
model.fit(train_data, epochs=20)

Epoch 1/20


      1/Unknown - 1s 1s/step - loss: 0.6683 - accuracy: 0.6667

     11/Unknown - 1s 5ms/step - loss: 0.6410 - accuracy: 0.6504

     22/Unknown - 1s 5ms/step - loss: 0.6106 - accuracy: 0.6667

     33/Unknown - 1s 5ms/step - loss: 0.5839 - accuracy: 0.7028

     44/Unknown - 1s 5ms/step - loss: 0.5680 - accuracy: 0.7168

53/53 [==============================] - 2s 11ms/step - loss: 0.5391 - accuracy: 0.7400


Epoch 2/20


 1/53 [..............................] - ETA: 1s - loss: 0.4875 - accuracy: 0.8333

12/53 [=====>........................] - ETA: 0s - loss: 0.4127 - accuracy: 0.8264

23/53 [============>.................] - ETA: 0s - loss: 0.4213 - accuracy: 0.8188

34/53 [==================>...........] - ETA: 0s - loss: 0.4387 - accuracy: 0.8088

45/53 [========================>.....] - ETA: 0s - loss: 0.4343 - accuracy: 0.8093

53/53 [==============================] - 0s 5ms/step - loss: 0.4326 - accuracy: 0.8086


Epoch 3/20


 1/53 [..............................] - ETA: 1s - loss: 0.4417 - accuracy: 0.8333

12/53 [=====>........................] - ETA: 0s - loss: 0.4676 - accuracy: 0.7639

23/53 [============>.................] - ETA: 0s - loss: 0.4455 - accuracy: 0.7940

34/53 [==================>...........] - ETA: 0s - loss: 0.4176 - accuracy: 0.7995

45/53 [========================>.....] - ETA: 0s - loss: 0.4293 - accuracy: 0.7985

53/53 [==============================] - 0s 5ms/step - loss: 0.4255 - accuracy: 0.8022


Epoch 4/20


 1/53 [..............................] - ETA: 1s - loss: 0.4468 - accuracy: 0.8333

12/53 [=====>........................] - ETA: 0s - loss: 0.3972 - accuracy: 0.8194

23/53 [============>.................] - ETA: 0s - loss: 0.3898 - accuracy: 0.8370

34/53 [==================>...........] - ETA: 0s - loss: 0.3946 - accuracy: 0.8382

45/53 [========================>.....] - ETA: 0s - loss: 0.4074 - accuracy: 0.8267

53/53 [==============================] - 0s 5ms/step - loss: 0.4080 - accuracy: 0.8198


Epoch 5/20


 1/53 [..............................] - ETA: 1s - loss: 0.2231 - accuracy: 0.9167

12/53 [=====>........................] - ETA: 0s - loss: 0.3323 - accuracy: 0.8519

23/53 [============>.................] - ETA: 0s - loss: 0.3836 - accuracy: 0.8277

34/53 [==================>...........] - ETA: 0s - loss: 0.3867 - accuracy: 0.8346

45/53 [========================>.....] - ETA: 0s - loss: 0.3923 - accuracy: 0.8249

53/53 [==============================] - 0s 5ms/step - loss: 0.4069 - accuracy: 0.8182


Epoch 6/20


 1/53 [..............................] - ETA: 1s - loss: 0.3279 - accuracy: 0.9167

11/53 [=====>........................] - ETA: 0s - loss: 0.3201 - accuracy: 0.8788

22/53 [===========>..................] - ETA: 0s - loss: 0.3672 - accuracy: 0.8510

33/53 [=================>............] - ETA: 0s - loss: 0.4020 - accuracy: 0.8191

44/53 [=======================>......] - ETA: 0s - loss: 0.4090 - accuracy: 0.8170

53/53 [==============================] - 0s 5ms/step - loss: 0.3985 - accuracy: 0.8198


Epoch 7/20


 1/53 [..............................] - ETA: 1s - loss: 0.5250 - accuracy: 0.8333

12/53 [=====>........................] - ETA: 0s - loss: 0.4647 - accuracy: 0.8074

23/53 [============>.................] - ETA: 0s - loss: 0.4272 - accuracy: 0.8090

34/53 [==================>...........] - ETA: 0s - loss: 0.4096 - accuracy: 0.8120

45/53 [========================>.....] - ETA: 0s - loss: 0.3962 - accuracy: 0.8192

53/53 [==============================] - 0s 5ms/step - loss: 0.3854 - accuracy: 0.8325


Epoch 8/20


 1/53 [..............................] - ETA: 1s - loss: 0.2195 - accuracy: 1.0000

12/53 [=====>........................] - ETA: 0s - loss: 0.4952 - accuracy: 0.7852

23/53 [============>.................] - ETA: 0s - loss: 0.4533 - accuracy: 0.7940

34/53 [==================>...........] - ETA: 0s - loss: 0.4169 - accuracy: 0.8095

45/53 [========================>.....] - ETA: 0s - loss: 0.3853 - accuracy: 0.8305

53/53 [==============================] - 0s 5ms/step - loss: 0.3843 - accuracy: 0.8341


Epoch 9/20


 1/53 [..............................] - ETA: 1s - loss: 0.3177 - accuracy: 0.8333

12/53 [=====>........................] - ETA: 0s - loss: 0.3070 - accuracy: 0.8889

23/53 [============>.................] - ETA: 0s - loss: 0.3514 - accuracy: 0.8502

34/53 [==================>...........] - ETA: 0s - loss: 0.3941 - accuracy: 0.8271

45/53 [========================>.....] - ETA: 0s - loss: 0.3809 - accuracy: 0.8418

53/53 [==============================] - 0s 5ms/step - loss: 0.3823 - accuracy: 0.8389


Epoch 10/20


 1/53 [..............................] - ETA: 1s - loss: 0.5376 - accuracy: 0.7500

12/53 [=====>........................] - ETA: 0s - loss: 0.3005 - accuracy: 0.8889

23/53 [============>.................] - ETA: 0s - loss: 0.3093 - accuracy: 0.8696

34/53 [==================>...........] - ETA: 0s - loss: 0.3450 - accuracy: 0.8505

45/53 [========================>.....] - ETA: 0s - loss: 0.3690 - accuracy: 0.8426

53/53 [==============================] - 0s 5ms/step - loss: 0.3745 - accuracy: 0.8389


Epoch 11/20


 1/53 [..............................] - ETA: 1s - loss: 0.4023 - accuracy: 0.8333

12/53 [=====>........................] - ETA: 0s - loss: 0.3738 - accuracy: 0.8611

23/53 [============>.................] - ETA: 0s - loss: 0.3559 - accuracy: 0.8587

34/53 [==================>...........] - ETA: 0s - loss: 0.3532 - accuracy: 0.8596

45/53 [========================>.....] - ETA: 0s - loss: 0.3805 - accuracy: 0.8362

53/53 [==============================] - 0s 5ms/step - loss: 0.3669 - accuracy: 0.8485


Epoch 12/20


 1/53 [..............................] - ETA: 1s - loss: 0.5077 - accuracy: 0.8333

12/53 [=====>........................] - ETA: 0s - loss: 0.3628 - accuracy: 0.8611

23/53 [============>.................] - ETA: 0s - loss: 0.3401 - accuracy: 0.8659

34/53 [==================>...........] - ETA: 0s - loss: 0.3613 - accuracy: 0.8505

45/53 [========================>.....] - ETA: 0s - loss: 0.3703 - accuracy: 0.8380

53/53 [==============================] - 0s 5ms/step - loss: 0.3588 - accuracy: 0.8485


Epoch 13/20


 1/53 [..............................] - ETA: 1s - loss: 0.4509 - accuracy: 0.8333

12/53 [=====>........................] - ETA: 0s - loss: 0.3770 - accuracy: 0.8403

23/53 [============>.................] - ETA: 0s - loss: 0.3351 - accuracy: 0.8539

34/53 [==================>...........] - ETA: 0s - loss: 0.3480 - accuracy: 0.8496

45/53 [========================>.....] - ETA: 0s - loss: 0.3384 - accuracy: 0.8569

53/53 [==============================] - 0s 5ms/step - loss: 0.3673 - accuracy: 0.8485


Epoch 14/20


 1/53 [..............................] - ETA: 1s - loss: 0.0941 - accuracy: 1.0000

12/53 [=====>........................] - ETA: 0s - loss: 0.3002 - accuracy: 0.8819

23/53 [============>.................] - ETA: 0s - loss: 0.3212 - accuracy: 0.8732

34/53 [==================>...........] - ETA: 0s - loss: 0.3322 - accuracy: 0.8627

45/53 [========================>.....] - ETA: 0s - loss: 0.3446 - accuracy: 0.8512

53/53 [==============================] - 0s 5ms/step - loss: 0.3508 - accuracy: 0.8485


Epoch 15/20


 1/53 [..............................] - ETA: 1s - loss: 0.1755 - accuracy: 1.0000

12/53 [=====>........................] - ETA: 0s - loss: 0.3584 - accuracy: 0.8542

23/53 [============>.................] - ETA: 0s - loss: 0.3308 - accuracy: 0.8659

34/53 [==================>...........] - ETA: 0s - loss: 0.3301 - accuracy: 0.8578

45/53 [========================>.....] - ETA: 0s - loss: 0.3415 - accuracy: 0.8550

53/53 [==============================] - 0s 5ms/step - loss: 0.3538 - accuracy: 0.8485


Epoch 16/20


 1/53 [..............................] - ETA: 1s - loss: 0.4740 - accuracy: 0.7500

12/53 [=====>........................] - ETA: 0s - loss: 0.3545 - accuracy: 0.8472

23/53 [============>.................] - ETA: 0s - loss: 0.3542 - accuracy: 0.8406

34/53 [==================>...........] - ETA: 0s - loss: 0.3529 - accuracy: 0.8480

45/53 [========================>.....] - ETA: 0s - loss: 0.3501 - accuracy: 0.8512

53/53 [==============================] - 0s 5ms/step - loss: 0.3496 - accuracy: 0.8517


Epoch 17/20


 1/53 [..............................] - ETA: 1s - loss: 0.3710 - accuracy: 0.9167

12/53 [=====>........................] - ETA: 0s - loss: 0.3527 - accuracy: 0.8741

23/53 [============>.................] - ETA: 0s - loss: 0.3186 - accuracy: 0.8876

34/53 [==================>...........] - ETA: 0s - loss: 0.3396 - accuracy: 0.8647

45/53 [========================>.....] - ETA: 0s - loss: 0.3480 - accuracy: 0.8588

53/53 [==============================] - 0s 5ms/step - loss: 0.3439 - accuracy: 0.8612


Epoch 18/20


 1/53 [..............................] - ETA: 1s - loss: 0.5029 - accuracy: 0.7500

12/53 [=====>........................] - ETA: 0s - loss: 0.3754 - accuracy: 0.8194

23/53 [============>.................] - ETA: 0s - loss: 0.3854 - accuracy: 0.8188

34/53 [==================>...........] - ETA: 0s - loss: 0.3582 - accuracy: 0.8396

45/53 [========================>.....] - ETA: 0s - loss: 0.3528 - accuracy: 0.8418

53/53 [==============================] - 0s 5ms/step - loss: 0.3464 - accuracy: 0.8469


Epoch 19/20


 1/53 [..............................] - ETA: 1s - loss: 0.3759 - accuracy: 0.7500

12/53 [=====>........................] - ETA: 0s - loss: 0.3410 - accuracy: 0.8542

23/53 [============>.................] - ETA: 0s - loss: 0.3714 - accuracy: 0.8370

34/53 [==================>...........] - ETA: 0s - loss: 0.3416 - accuracy: 0.8578

45/53 [========================>.....] - ETA: 0s - loss: 0.3510 - accuracy: 0.8574

53/53 [==============================] - 0s 5ms/step - loss: 0.3457 - accuracy: 0.8549


Epoch 20/20


 1/53 [..............................] - ETA: 1s - loss: 0.2682 - accuracy: 0.9167

12/53 [=====>........................] - ETA: 0s - loss: 0.2616 - accuracy: 0.9028

23/53 [============>.................] - ETA: 0s - loss: 0.3282 - accuracy: 0.8659

34/53 [==================>...........] - ETA: 0s - loss: 0.3360 - accuracy: 0.8554

45/53 [========================>.....] - ETA: 0s - loss: 0.3237 - accuracy: 0.8644

53/53 [==============================] - 0s 5ms/step - loss: 0.3330 - accuracy: 0.8660


当模型训练完成的时候，你可以在测试集 `test_data` 上检查准确性。

In [19]:
test_loss, test_accuracy = model.evaluate(test_data)

print('\n\nTest Loss {}, Test Accuracy {}'.format(test_loss, test_accuracy))

      1/Unknown - 0s 364ms/step - loss: 0.5226 - accuracy: 0.9167

     13/Unknown - 0s 4ms/step - loss: 0.3757 - accuracy: 0.8462  

22/22 [==============================] - 0s 5ms/step - loss: 0.4482 - accuracy: 0.8030




Test Loss 0.4481576979160309, Test Accuracy 0.8030303120613098


使用 `tf.keras.Model.predict` 推断一个批次或多个批次的标签。

In [20]:
predictions = model.predict(test_data)

# 显示部分结果
for prediction, survived in zip(predictions[:10], list(test_data)[0][1][:10]):
  print("Predicted survival: {:.2%}".format(prediction[0]),
        " | Actual outcome: ",
        ("SURVIVED" if bool(survived) else "DIED"))


      1/Unknown - 0s 269ms/step

     17/Unknown - 0s 3ms/step  

22/22 [==============================] - 0s 4ms/step


Predicted survival: 90.08%  | Actual outcome:  SURVIVED
Predicted survival: 0.97%  | Actual outcome:  SURVIVED
Predicted survival: 0.98%  | Actual outcome:  DIED
Predicted survival: 10.06%  | Actual outcome:  SURVIVED
Predicted survival: 62.49%  | Actual outcome:  DIED
Predicted survival: 62.38%  | Actual outcome:  SURVIVED
Predicted survival: 11.18%  | Actual outcome:  SURVIVED
Predicted survival: 60.31%  | Actual outcome:  SURVIVED
Predicted survival: 9.72%  | Actual outcome:  DIED
Predicted survival: 21.93%  | Actual outcome:  DIED
